<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>boton logout</name>
   <tag></tag>
   <elementGuidId>bd4672d4-4149-4495-b494-eec0b9c47045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='logOutFuncLink();']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.logoutIconLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Cerrar Sesión&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>69f1060d-6985-41b7-8f06-b1b001adf1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mcm-web-render/logout.jsp</value>
      <webElementGuid>01f0351c-4b05-45b6-b1c8-f70bd004ad3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logoutIconLink</value>
      <webElementGuid>028e2184-f725-4737-acbd-96f1a57d8b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cerrar Sesión</value>
      <webElementGuid>c96e8e04-0afb-49eb-bce1-f4c8a9d43a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>logOutFuncLink();</value>
      <webElementGuid>614d568f-cf62-442f-bff5-10fdf4e047fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quickMenu&quot;)/table[@class=&quot;iconToolsCtnr&quot;]/tbody[1]/tr[1]/td[@class=&quot;center&quot;]/table[1]/tbody[1]/tr[1]/td[2]/a[@class=&quot;logoutIconLink&quot;]</value>
      <webElementGuid>3627928a-6f00-4771-a968-69819b6c1564</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='logOutFuncLink();']</value>
      <webElementGuid>bc5f2c61-e2d3-444a-9981-12d9bc7cdf7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quickMenu']/table/tbody/tr/td[2]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>0f464565-7373-43cb-a6d8-5f894e4bdd9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salir'])[1]/following::a[1]</value>
      <webElementGuid>15f3b112-05e0-48d6-9ae7-9b3bb9dca433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GONZALO CAMBIASO'])[1]/following::a[2]</value>
      <webElementGuid>ef4f1fed-1d4a-45c4-9121-465d1af8af45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consolidado'])[1]/preceding::a[1]</value>
      <webElementGuid>deb74241-7de8-4994-978b-8ea4ef3472ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transferencias'])[1]/preceding::a[1]</value>
      <webElementGuid>ca16fc8b-de85-4b5e-bd0f-43cadb6237d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/mcm-web-render/logout.jsp')])[2]</value>
      <webElementGuid>7f56e1fb-5977-4356-a872-5abedd0dddbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>5a027c0c-83a7-483e-90f5-25ccba5583d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mcm-web-render/logout.jsp' and @title = 'Cerrar Sesión']</value>
      <webElementGuid>0ef7b6f7-2b26-42ad-8d4b-e23d03be2cb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
