<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>boton menu transferencias</name>
   <tag></tag>
   <elementGuidId>79d7fe3e-3c73-4f07-a8cf-36619bedaf8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(.,'Transferencias')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu2570_BUedEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Transferencias&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>575ddcb3-ad7e-402d-8e08-b1f9d9d80a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dijitReset dijitInline dijitMenuItem dijitMenuItemLabel dijitHorizontalSubMenuItem dijitHorizontalSubMenuItemHover dijitHover dijitHorizontalSubMenuItemFocused dijitHorizontalSubMenuItemHoverFocused dijitHoverFocused dijitFocused dijitMenuItemSelected</value>
      <webElementGuid>6f3e55e5-3087-45ad-aa08-a3d9fc4551db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-attach-point</name>
      <type>Main</type>
      <value>focusNode</value>
      <webElementGuid>7ddd82b8-6aeb-4a0f-ac85-794b8e5403e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>08cede6b-f8c9-425d-a789-beb197220d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>15a7832b-2881-4f21-80ab-4341042ba943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Transferencias </value>
      <webElementGuid>9c64edb6-47cd-40b5-885a-a94aa5756cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu2570_BUedEl</value>
      <webElementGuid>cde52605-d1bf-4314-bac2-afef70f5f7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>widgetid</name>
      <type>Main</type>
      <value>menu2570_BUedEl</value>
      <webElementGuid>da499051-4ade-47eb-86ab-c1ed453f4260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	Transferencias
</value>
      <webElementGuid>5c0c34cf-ec69-48fe-9335-4ae7e57f283f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2570_BUedEl&quot;)</value>
      <webElementGuid>f148602a-aa01-494b-9af8-47daab85724b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='menu2570_BUedEl']</value>
      <webElementGuid>d5696b9f-6608-4f0b-ad9d-6e568189b0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topMenu']/div[2]</value>
      <webElementGuid>43afd5ce-1411-4895-a826-20ed98ab3cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consolidado'])[1]/following::div[1]</value>
      <webElementGuid>5e5aabd7-4da1-48d0-986b-6912e169c7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salir'])[1]/following::div[4]</value>
      <webElementGuid>5c21466e-852c-4261-9356-35bae455bf0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beneficiarios'])[1]/preceding::div[1]</value>
      <webElementGuid>80d5eaac-1830-4d76-99f6-c4c8a8e67a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>982dccb6-a535-472a-ab48-2747e07182c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'menu2570_BUedEl' and (text() = '
	Transferencias
' or . = '
	Transferencias
')]</value>
      <webElementGuid>7e224a98-1f3b-453e-8f05-b8eadc683bd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
