<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cuenta debito</name>
   <tag></tag>
   <elementGuidId>be55b0a3-6c18-4768-aca4-b896d4cb8bf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='dijit_MenuItem_6_text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dijit_MenuItem_6_text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;4010352294 - CTA-PRUEBABARRIDO - USD - 831.75 - REG. JURIDICA LOCAL&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>41642a6c-2e17-4969-ad19-b14216fcef3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dijitReset dijitMenuItemLabel</value>
      <webElementGuid>da9abb33-4e01-4f9b-b4fa-b996f74369bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7fb26327-10b9-4693-b205-9a0fe8d898f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-attach-point</name>
      <type>Main</type>
      <value>containerNode,textDirNode</value>
      <webElementGuid>094ab26e-afa0-4b47-b811-e14b08af15fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dijit_MenuItem_6_text</value>
      <webElementGuid>d0769cb0-851b-4c45-aae6-30d22edd70cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4010352294 - CTA-PRUEBABARRIDO - USD -               831.75 - REG. JURIDICA LOCAL</value>
      <webElementGuid>92b99f9c-5068-4f00-a531-ae1debb8719b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dijit_MenuItem_6_text&quot;)</value>
      <webElementGuid>71c49952-5dd8-4ad3-885b-fe25ae5d84d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='dijit_MenuItem_6_text']</value>
      <webElementGuid>599e88a7-a57b-4715-a895-c4f44ff44527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dijit_MenuItem_6']/td[2]</value>
      <webElementGuid>90afe2d3-26f9-4ad4-9bbd-aa42665bd953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[9]/following::td[2]</value>
      <webElementGuid>86c0523f-4c50-4222-943d-8c120787421b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[8]/following::td[6]</value>
      <webElementGuid>9a090c7b-1acb-4f3c-8af3-0fa59f2281bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[10]/preceding::td[2]</value>
      <webElementGuid>4fa348e8-8dd7-4722-aedb-4732d7d57d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[11]/preceding::td[6]</value>
      <webElementGuid>065e819b-1243-4067-9ac6-600cf08f3731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>1e4ef4ff-56d5-4d3b-a5a1-5c876e76226c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'dijit_MenuItem_6_text' and (text() = '4010352294 - CTA-PRUEBABARRIDO - USD -               831.75 - REG. JURIDICA LOCAL' or . = '4010352294 - CTA-PRUEBABARRIDO - USD -               831.75 - REG. JURIDICA LOCAL')]</value>
      <webElementGuid>d1204dff-8f12-4936-be01-b007672df968</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
