<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>boton menu transferencias</name>
   <tag></tag>
   <elementGuidId>79d7fe3e-3c73-4f07-a8cf-36619bedaf8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu2570_BUedEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu2570_BUedEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Transferencias&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6a217e7a-8c11-4243-ba20-eb7de41a6939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dijitReset dijitInline dijitMenuItem dijitMenuItemLabel dijitHorizontalSubMenuItem dijitHorizontalSubMenuItemHover dijitHover dijitHorizontalSubMenuItemFocused dijitHorizontalSubMenuItemHoverFocused dijitHoverFocused dijitFocused dijitMenuItemSelected</value>
      <webElementGuid>026ca199-2157-4d28-9dc8-f98045e129ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-attach-point</name>
      <type>Main</type>
      <value>focusNode</value>
      <webElementGuid>dd707e9d-7005-4d66-aab7-84745ddf3727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>4f994e83-0170-4ad8-9ec6-01972e8b5147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9d1c9fa9-e984-4d61-84e2-406846129bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Transferencias </value>
      <webElementGuid>52e5df86-be37-42fd-b227-93b385f7bd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu2570_BUedEl</value>
      <webElementGuid>4b211b9d-3ee1-48e6-b2ba-3e965d94ed07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>widgetid</name>
      <type>Main</type>
      <value>menu2570_BUedEl</value>
      <webElementGuid>88dcd92b-2040-4103-8184-16a049fa3935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	Transferencias
</value>
      <webElementGuid>34b45c0b-5705-49ed-907a-3cebaf72ebfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2570_BUedEl&quot;)</value>
      <webElementGuid>59089fe4-5dbd-4e19-b0fe-2bdba170e761</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='menu2570_BUedEl']</value>
      <webElementGuid>b492a7ef-f92f-47aa-b09e-c59a51f34cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topMenu']/div[2]</value>
      <webElementGuid>17b898d7-aad5-4e44-9d90-b96ea8aa53ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consolidado'])[1]/following::div[1]</value>
      <webElementGuid>d22c5905-03f3-49e7-86ac-c6c7cb7bbec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salir'])[1]/following::div[4]</value>
      <webElementGuid>af1f5fcd-d68c-4940-8017-6b905dd1bb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beneficiarios'])[1]/preceding::div[1]</value>
      <webElementGuid>84d82778-a167-4957-8ac4-0e6634c94a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>8e7be667-2a28-49fd-9390-146bab129711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'menu2570_BUedEl' and (text() = '
	Transferencias
' or . = '
	Transferencias
')]</value>
      <webElementGuid>d7220778-d3fc-43ba-a61d-23a72d2f41e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
