<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ingresar Concepto</name>
   <tag></tag>
   <elementGuidId>f3fb283f-a92d-4e9a-9558-d289f9f6c720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ec_fisa_widget_TextArea_0_textArea']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ec_fisa_widget_TextArea_0_textArea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Concepto de la transacción&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fe7a9520-8e70-4fc2-8315-d1eb39b686d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-attach-point</name>
      <type>Main</type>
      <value>focusNode,containerNode,textbox</value>
      <webElementGuid>2e795bc2-01f9-43e7-82eb-0eb123f3cead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>984d720b-3789-482d-baa1-31fd117b61bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dijitTextBox dijitTextArea dijitTextBoxHover dijitTextAreaHover dijitHover dijitTextBoxFocused dijitTextAreaFocused dijitTextBoxHoverFocused dijitTextAreaHoverFocused dijitHoverFocused dijitFocused</value>
      <webElementGuid>5b140ad7-ed68-4f3d-9af4-20bad6a7b679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ec_fisa_widget_TextArea_0_textArea</value>
      <webElementGuid>54ca89ac-f493-4f7a-9b9b-7116fc39ed9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0abe2038-c297-4112-9df3-f9e640bcdb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>de3453be-c5e1-4a64-845c-8c710dcad7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>02c22bdf-fdf4-4931-9c4c-84c4ccca7f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Concepto de la transacción</value>
      <webElementGuid>5025a1b1-9fac-4602-a35f-d95e101b7b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>143</value>
      <webElementGuid>5aab0d35-bf55-4c99-a5db-dd61341724d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>widgetid</name>
      <type>Main</type>
      <value>ec_fisa_widget_TextArea_0_textArea</value>
      <webElementGuid>47c78514-9e26-4162-855f-8d88bda1a207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ec_fisa_widget_TextArea_0_textArea&quot;)</value>
      <webElementGuid>a0b35dba-1458-4bc7-a4ee-104cc1ad322d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ec_fisa_widget_TextArea_0_textArea']</value>
      <webElementGuid>a6cfc55c-5cca-4f6b-89ba-a6b590b61acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ec_fisa_widget_TextArea_0']/textarea</value>
      <webElementGuid>f83ea6da-179b-43ce-b787-6212cb012914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>180e7df9-b42e-477e-ac59-a5f4b8652017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ec_fisa_widget_TextArea_0_textArea' and @title = 'Concepto de la transacción']</value>
      <webElementGuid>c3cb4a22-e019-4342-b8ea-5c5707834227</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
