<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buton Aceptar</name>
   <tag></tag>
   <elementGuidId>bbd51a41-bbff-4fcf-b751-5ba318e2b67f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dijit_form_Button_20_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Aceptar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Aceptar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7c32fbc9-6843-48e2-943f-5540722acc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dijitReset dijitInline dijitButtonText</value>
      <webElementGuid>d3bfea6c-8b2e-4575-be26-00561fcdbbb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dijit_form_Button_20_label</value>
      <webElementGuid>898312ad-71af-4aaa-988a-3b7ccd37e048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-attach-point</name>
      <type>Main</type>
      <value>containerNode</value>
      <webElementGuid>d029d683-9c30-41f2-8716-d3857fa5e980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>6a59ee73-9e8b-4081-a1e5-d9f791b1ff8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dijit_form_Button_20_label&quot;)</value>
      <webElementGuid>ad6b9012-907a-45fc-b374-e53ac004c7e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='dijit_form_Button_20_label']</value>
      <webElementGuid>5a652131-7359-4bc6-b44e-3e1849cc8c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='dijit_form_Button_20']/span[3]</value>
      <webElementGuid>c43e7261-d819-48e9-858a-f4fd1a5a66cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='●'])[5]/following::span[1]</value>
      <webElementGuid>9c7b9411-376d-4709-ab97-758f79d37343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::span[6]</value>
      <webElementGuid>782bb627-f2a7-4219-9b1e-f29d7b791707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat'])[1]/preceding::span[1]</value>
      <webElementGuid>49a31f54-7ff8-424c-a9d6-48811f1cdd9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© CredicorpBank, 2014 | Entidad Supervisada por la'])[1]/preceding::span[2]</value>
      <webElementGuid>4806919c-f544-40e3-ad40-224e45b656ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aceptar']/parent::*</value>
      <webElementGuid>72d840c1-7d0a-4ee2-9c89-e2aa083da72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span/span/span/span[3]</value>
      <webElementGuid>10d32842-faa7-4e6c-b72e-1752f36467ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'dijit_form_Button_20_label' and (text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>9c1dad35-96c9-46ea-816e-7ac5fa657edd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
