<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ingresar Cuenta Destino</name>
   <tag></tag>
   <elementGuidId>4d356b72-81c7-4a92-8622-0297183a71e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ec_fisa_widget_TextBox_1_textBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ec_fisa_widget_TextBox_1_textBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Número de Cuenta Beneficiaria de la Transferencia&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd37f362-ba5e-497a-8f43-7227f6e07163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dijitReset dijitInputInner</value>
      <webElementGuid>0b5b95da-46e1-4d8f-b283-08da14bccf95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-attach-point</name>
      <type>Main</type>
      <value>textbox,focusNode</value>
      <webElementGuid>2e74c43c-37d0-4366-9755-85d106b2481c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3b4d41b0-a65b-48a7-b1fe-803e23d3ab84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>553c4750-5f8a-4625-af13-dc162c7c87ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ec_fisa_widget_TextBox_1_textBox</value>
      <webElementGuid>98d06abb-ab47-4fb7-b812-e7f94016b6b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0c65e4a3-bd56-4bc5-b227-aae2a986fa99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>4033dddf-d1b3-416b-81a6-a548d2c3c8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Número de Cuenta Beneficiaria de la Transferencia</value>
      <webElementGuid>31e5efda-45d6-4b64-a1c0-46496a057e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ec_fisa_widget_TextBox_1_textBox&quot;)</value>
      <webElementGuid>c2052205-e452-4592-a644-12dab5125cc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ec_fisa_widget_TextBox_1_textBox']</value>
      <webElementGuid>c84d2348-4f89-4d97-8e33-de3e6ef6cc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widget_ec_fisa_widget_TextBox_1_textBox']/div/input</value>
      <webElementGuid>d83fae51-f357-46ad-bdd8-03b94c5cddab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/input</value>
      <webElementGuid>383e99aa-9aca-4e7d-8d5e-4953d6865e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ec_fisa_widget_TextBox_1_textBox' and @title = 'Número de Cuenta Beneficiaria de la Transferencia']</value>
      <webElementGuid>d728c10c-ca10-4eae-b2fc-42ba47e45131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
