<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ingresar cliente</name>
   <tag></tag>
   <elementGuidId>883c6ee5-7b0d-4f1b-be66-be4f5ca8037c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ec_fisa_widget_TextBox_1_textBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ec_fisa_widget_TextBox_1_textBox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Número de Cliente para pago IDAAN&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>249e0a14-8f86-43d5-b18d-4f66e916cef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dijitReset dijitInputInner</value>
      <webElementGuid>6f0aa530-6eb9-41a7-a12f-faee7f0a5e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-attach-point</name>
      <type>Main</type>
      <value>textbox,focusNode</value>
      <webElementGuid>c034886c-496c-4586-af92-5eadddfe8e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ff9c752d-afaf-435a-a772-1dcc3038a4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aecbcd83-dd44-4bf4-ad97-6638dcca8fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ec_fisa_widget_TextBox_1_textBox</value>
      <webElementGuid>7a9a17d7-cd30-49e5-aecd-1a8740a10a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>30b7f331-b7ff-472f-b267-7abffe9fc219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>6dacf662-210b-4239-ae1b-5ccd11032b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Número de Cliente para pago IDAAN</value>
      <webElementGuid>2077b03b-5c5c-4637-8d7e-bc8009f33e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ec_fisa_widget_TextBox_1_textBox&quot;)</value>
      <webElementGuid>fb9aa823-36a2-4abb-a531-1c1c2f6c32ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ec_fisa_widget_TextBox_1_textBox']</value>
      <webElementGuid>251f91d1-2362-4cfc-a632-907aae7d2eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widget_ec_fisa_widget_TextBox_1_textBox']/div/input</value>
      <webElementGuid>93154e39-0a16-444b-80ef-3fe744aa9c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/table/tbody/tr/td/div/div/input</value>
      <webElementGuid>d2d92048-6385-4956-90db-ad4178b7dc23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ec_fisa_widget_TextBox_1_textBox' and @title = 'Número de Cliente para pago IDAAN']</value>
      <webElementGuid>6903983b-1c57-4e39-b337-cc8707d789ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
