<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ingresar concepto</name>
   <tag></tag>
   <elementGuidId>f79e983d-b160-484c-8997-68f7aafb8ce5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ec_fisa_widget_TextArea_0_textArea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ec_fisa_widget_TextArea_0_textArea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Concepto de la transacción&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>afc03ec6-e7dd-41e1-82cb-fcde68e6405f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-attach-point</name>
      <type>Main</type>
      <value>focusNode,containerNode,textbox</value>
      <webElementGuid>d7172340-226f-4ad4-96ba-4c4cba8a6f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a0745d0f-fbf9-4baf-9f88-b8fcc990c6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dijitTextBox dijitTextArea dijitTextBoxHover dijitTextAreaHover dijitHover dijitTextBoxFocused dijitTextAreaFocused dijitTextBoxHoverFocused dijitTextAreaHoverFocused dijitHoverFocused dijitFocused</value>
      <webElementGuid>989d5b58-6224-4f55-8a09-83e08b250a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ec_fisa_widget_TextArea_0_textArea</value>
      <webElementGuid>d94eb259-94d8-4f2f-a8bd-7c61d656fdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1df5d4c8-f888-416c-a0ea-c17406000398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>182cf3ec-ef83-45b4-ae37-c3e2cf3ce8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>1bcb47bd-6834-47c8-8315-c38fcb256cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Concepto de la transacción</value>
      <webElementGuid>2926ce79-00c9-430c-99aa-94e47b709a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>143</value>
      <webElementGuid>3b636a0b-bcff-4400-90f4-98ee5ff35f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>widgetid</name>
      <type>Main</type>
      <value>ec_fisa_widget_TextArea_0_textArea</value>
      <webElementGuid>2d696087-b6cb-4b02-886b-da7b0b0c5bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ec_fisa_widget_TextArea_0_textArea&quot;)</value>
      <webElementGuid>27111fd5-abbd-4dfe-97e5-4f468833355a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ec_fisa_widget_TextArea_0_textArea']</value>
      <webElementGuid>2d727db2-af06-4237-99d2-9cc32a3ca8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ec_fisa_widget_TextArea_0']/textarea</value>
      <webElementGuid>36d6339e-0014-4ca4-afd3-dd2491cd0752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f628a184-fd97-4cea-a2e2-b2ed08ebc994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ec_fisa_widget_TextArea_0_textArea' and @title = 'Concepto de la transacción']</value>
      <webElementGuid>ef897506-fefb-418b-971b-0cc31b8cfa78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
