<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu Pagos</name>
   <tag></tag>
   <elementGuidId>09f7585e-d400-4579-81ae-4ab573a9581d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu2572_ZydGfF_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='menu2572_ZydGfF_text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Pagos&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e28396ee-64ef-4e6f-b214-dc75e8dc710d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-attach-point</name>
      <type>Main</type>
      <value>containerNode,textDirNode</value>
      <webElementGuid>95cd8253-25c5-4fa0-964a-b60c5f19db45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu2572_ZydGfF_text</value>
      <webElementGuid>a9ac365a-8b04-4f1d-be1c-9b5fd2c0474a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pagos</value>
      <webElementGuid>6c5c4c0d-2485-474d-8f23-9a8ebfa20479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu2572_ZydGfF_text&quot;)</value>
      <webElementGuid>baacded4-d161-4ebf-8d7c-0067689f5d35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='menu2572_ZydGfF_text']</value>
      <webElementGuid>ba1eca66-6361-40a4-a691-834d512ce686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu2572_ZydGfF']/span</value>
      <webElementGuid>462f4d73-2e49-493d-86c5-22036b0dc549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beneficiarios'])[1]/following::span[1]</value>
      <webElementGuid>00641b17-a298-4033-b7f0-4717ca1b5e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transferencias'])[1]/following::span[2]</value>
      <webElementGuid>ae91f5f2-0432-4e1d-9b75-ec5bc3e41006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicios'])[1]/preceding::span[1]</value>
      <webElementGuid>11902a3b-a4bd-4beb-9ea0-3eea7954f66d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seguridad'])[1]/preceding::span[2]</value>
      <webElementGuid>32abe522-9d02-4c4a-9a9c-a491f534415e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pagos']/parent::*</value>
      <webElementGuid>b53fdfdc-200b-41a9-ae2a-a0755ddb341f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span</value>
      <webElementGuid>a4183509-19a5-4b96-bc68-67fd03fa20e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'menu2572_ZydGfF_text' and (text() = 'Pagos' or . = 'Pagos')]</value>
      <webElementGuid>97c2ebe3-9c48-4c95-9d35-591dc755854e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
