<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pago de servicios</name>
   <tag></tag>
   <elementGuidId>616e4425-601f-44d1-b16f-bb4e06afdca4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_2561menu2601_GCveQK_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='_2561menu2601_GCveQK_text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Pago De Servicios&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3778c5b5-290c-42ad-a9dc-13e8c41dfa64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dijitReset dijitMenuItemLabel</value>
      <webElementGuid>b0b3e700-9ab0-45c0-a1d1-ee613e1a564d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>52becd9e-9bb7-4e81-883b-8ea2a4661554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-attach-point</name>
      <type>Main</type>
      <value>containerNode,textDirNode</value>
      <webElementGuid>d6775647-601b-4d75-9c6f-e4f15116708b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_2561menu2601_GCveQK_text</value>
      <webElementGuid>afae28c0-2264-450b-a0a7-fb0271015bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pago De Servicios</value>
      <webElementGuid>ee28b391-0353-4023-9ebd-31289b620a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_2561menu2601_GCveQK_text&quot;)</value>
      <webElementGuid>4a54e19b-97cb-4d3e-9e25-dd869ebd8dba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='_2561menu2601_GCveQK_text']</value>
      <webElementGuid>a6e59deb-1715-46a4-8ef1-7e0385af46e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='_2561menu2601_GCveQK']/td[2]</value>
      <webElementGuid>cdd0801e-6677-4e19-955e-ec0dd5d84a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::td[2]</value>
      <webElementGuid>e247b620-0e87-4e3d-93b6-8de655f7a079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::td[2]</value>
      <webElementGuid>4206bc26-3462-4bf0-bfc8-bd8004c6cb49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pago De Obligaciones'])[1]/preceding::td[4]</value>
      <webElementGuid>8e344d41-1d06-47f2-a474-c2867a982f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pago De Servicios']/parent::*</value>
      <webElementGuid>93cbd6b1-d18c-49a3-a3d8-fbe6f92086fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr/td[2]</value>
      <webElementGuid>ffc47290-30d4-4660-886d-b557112a8008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = '_2561menu2601_GCveQK_text' and (text() = 'Pago De Servicios' or . = 'Pago De Servicios')]</value>
      <webElementGuid>d6cb320f-419a-4acb-b197-74abc5e1985e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
