<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>seleciona cuenta debito</name>
   <tag></tag>
   <elementGuidId>8bb4989e-dba5-4496-b5a4-62d1e1074280</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dijit_MenuItem_23_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='dijit_MenuItem_23_text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;4021905515 - - USD - 2,945.56 - REGULAR NAT. LOCAL&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c57dd022-883e-451b-8dea-adc34960230d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dijitReset dijitMenuItemLabel</value>
      <webElementGuid>777badcf-da75-4c16-a926-c36f4cbc1db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7b2621d0-8679-4aac-946c-63828b2957b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-attach-point</name>
      <type>Main</type>
      <value>containerNode,textDirNode</value>
      <webElementGuid>e4a9cd28-4810-4b7d-be18-e78cbb929674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dijit_MenuItem_23_text</value>
      <webElementGuid>6f7a751b-9492-4e9d-aaf7-85f285c9f8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4021905515 - - USD -             2,945.56 - REGULAR NAT. LOCAL</value>
      <webElementGuid>80b9457f-aed9-4c9d-a209-97751e95cd3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dijit_MenuItem_23_text&quot;)</value>
      <webElementGuid>3c82d430-13a5-41f9-bd6c-8af88fbeec21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='dijit_MenuItem_23_text']</value>
      <webElementGuid>b796d0c8-b532-455e-9c91-6b13fe3bee94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dijit_MenuItem_23']/td[2]</value>
      <webElementGuid>c35de4b0-246e-4d24-8d56-e7f034a9570e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[24]/following::td[2]</value>
      <webElementGuid>2da6ed4f-0780-4a25-a957-1f7368c45064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione un ítem'])[3]/following::td[4]</value>
      <webElementGuid>6fe97a73-8941-4612-a618-3e9ac49e04f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[25]/preceding::td[2]</value>
      <webElementGuid>f6c803d5-8259-4d0a-9d60-473321f8bb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>9cddca1e-2fbb-46d7-8291-7d7a663c6c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'dijit_MenuItem_23_text' and (text() = '4021905515 - - USD -             2,945.56 - REGULAR NAT. LOCAL' or . = '4021905515 - - USD -             2,945.56 - REGULAR NAT. LOCAL')]</value>
      <webElementGuid>3224f24a-5092-4291-aa43-9dff07e5aa10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
